### PR TITLE
dist/etc/conf: Add mapping for nucleo-l476rg

### PR DESCRIPTION
**Pull request by ngandrass**
Added a mapping for the Nucleo-L476RG board.

See: https://www.st.com/en/evaluation-tools/nucleo-l476rg.html

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Can you post the results of the `tests/periph_gpio`?

**Comment by MrKevinWeiss** [comment]
Everything looks pretty good otherwise.

**Review by MrKevinWeiss — APPROVED** [review]
ACK!

**Comment by ngandrass** [comment]
Just to have it written down somewhere for the future... Explicitly setting `RESET` and `RESET_FLAGS` to the following values fixes the GPIO reset test issues:

```
RESET="python3 -m philip_pal --dut_reset"
RESET_FLAGS="${PHILIP_PORT}"
```

**Pull request merged**
