### PR TITLE
Jenkinsfile: Allow running RIOT tests

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
It turns out the `TESTS` parameter interferes with the env vars used in `make test`. This provides some better namespacing as well as prevents errors if results are empty.

Some cleanup as well.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
This fixes the nightlies as well.  Every night it will checkout master rf and riot.  It will add RIOT submodule update and a commit saying that it is updating with nightlies.  It will force push this to the nightlies branch (since we don't want to keep every nights updating nightlies commit).

Note that the nightlies are not really useful anymore but are needed to keep consistency with the current infrastructure.  They can be removed once everything is cleaned up,

**Comment by MrKevinWeiss** [comment]
The testing is being done on the nightlies branch as well.  after the build is run I will rerun to show that the additional "update RIOT submodule" commit is overwritten.

**Review by cgundogan — APPROVED** [review]
Code changes look good.  Tested together with @MrKevinWeiss and it works as expected.

**Comment by MrKevinWeiss** [comment]
Many thanks!

**Pull request merged**
