### PR TITLE
Add plotting script for accuracy timer benchmark

### PR DESCRIPTION
**Pull request by pokgak**
This PR adds the plotting script for accuracy timer benchmarks. I also included the fix to the resulting HTML file to convert `<br>` tags in the Plotly output to `<br />`.

This script is only for the accuracy timer benchmark, for now, more coming.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Do I need something to view the graphs after downloading the .html? I can see the data is there just nothing is being rendered on my browser.  I assume this will be a function of the new HiL website?

If @ozfox says it is OK then I am fine.

**Comment by pokgak** [comment]
The HTML file output from the pipeline is not a complete HTML file, only meant to be included using XSLT. However, you can remove the flag `--for-ci` from the command in `robot-html` in `Makefile.include` to get a full HTML that can be opened in a browser.

**Comment by pokgak** [comment]
@ozfox you might want to check if the HTML output from this PR can be used with XSLT.

**Comment by MrKevinWeiss** [comment]
Hmm, we can break that out late if we need control from the make level.  All good on my end.

**Comment by pokgak** [comment]
Ping @ozfox?

**Comment by ozfox** [comment]
@pokgak Accuracy plots look great! Works as expected..

**Review by MrKevinWeiss — APPROVED** [review]
ACK

**Pull request merged**
