### PR TITLE
conf/esp32-wroom-32: Add uart dev to env

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
It seems like we should enable the uart testing for the esp32, I don't know if it is possible or wired though...

Thanks to @yegorich for spotting it.

### CODE REVIEW

**Comment by yegorich** [comment]
frdm-kw41z, saml10-xpro and slstk3401a seem to have the same issue.

**Comment by MrKevinWeiss** [comment]
Ya but they also don't have an available second UART available.  The slstk3401a requires UART 2 not UART 1 but I will have to confirm wiring.

**Comment by MrKevinWeiss** [comment]
Ok, I need to confirm that the wires are plugged in though. Last I checked this wasn't passing.

**Comment by gschorcht** [comment]
At least the configuration
```
HIL_DUT_RX_PORT?=0
HIL_DUT_RX_PIN?=9

HIL_DUT_TX_PORT?=0
HIL_DUT_TX_PIN?=10
```
is correct. GPIO10 is UART1:TX and GPIO9 is UART1:RX. Wiring
```
esp32 GPIO10   ->  nucleo-f103rb PA10
esp32 GPIO9    ->  nucleo-f103rb PA9
```
works for me.

**Comment by MrKevinWeiss** [comment]
Good good, thanks!

**Comment by gschorcht** [comment]
@MrKevinWeiss Could you check the wiring, all tests fail at the moment in HIL. In my local installation, all tests pass with the current master

My wiring is
```
esp32 GPIO9/SD2 (UART1:RX)   ->  nucleo-f103rb PA9
esp32 GPIO10/SD3 (UART1:TX)  ->  nucleo-f103rb PA10
```
which corresponds to the configuration in `dist/etc/conf/esp32-wroom-32.env` if I'm right on how to interpret `HIL_DUT_RX/TX_PORT/PIN` definitions.

GPIO9 and GPIO10 are labeled SD2 and SD3 (data lines for QOUT/QIO flash mode) on some boards.

**Pull request merged**
