### PR TITLE
Add plotting scripts overhead

### PR DESCRIPTION
**Pull request by pokgak**
This PR adds the script to plot the results of overhead setting and removing timers. Example of how it will look like is attached in the zip file.

[overhead_plots.zip](https://github.com/RIOT-OS/RobotFW-tests/files/6216930/overhead_plots.zip)

depends on #99

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I manually triggered the CI
https://hil.riot-os.org/results/robotFW_tests/1/arduino-due/tests_xtimer_benchmarks/report

**Comment by MrKevinWeiss** [comment]
Plots look good

**Comment by MrKevinWeiss** [comment]
Maybe you can rebase again and I will rerun everything.  We should get this in before the robot v4 update.

**Comment by pokgak** [comment]
Rebased to master

**Comment by MrKevinWeiss** [comment]
Hmm something odd is happening with the frdm-k64f board... https://ci.riot-os.org/hil/blue/organizations/jenkins/robotFW_tests/detail/robotFW_tests/29/pipeline

I will rerun as it looks like maybe just a temporary interruption.

**Comment by MrKevinWeiss** [comment]
Hmmm I don't see the plots...

https://hil.riot-os.org/results/robotFW_tests/30/overview

Only the initial 2.

**Comment by pokgak** [comment]
I'll take a look at this today.

**Comment by pokgak** [comment]
I suspect this is due to how the page is built using XSLT. [This line][1] seems like it hardcodes the name of the files that are included on the page. 

@ozfox instead of hardcoding the names in a config file, is it possible to just go through all files in the `includes` folder and include them on the page?

[1]: https://github.com/RIOT-OS/RobotFW-frontend/blob/df4e6c284b55e371ab31f8a2d31515b9323e6bd6/pages.xml#L21

**Comment by ozfox** [comment]
> @ozfox instead of hardcoding the names in a config file, is it possible to just go through all files in the includes folder and include them on the page?

That is not possible with XSLT, all input data has to be read from xml files or passed to `xsltproc` as a parameter. That's the reason why it's set it in the config file as it separates it from the code, at least.

The alternative would be to pass a  `--param`or `--stringparam` when calling `xsltproc` in [RobotFW-frontend/scripts/xsltprocw.sh](https://github.com/RIOT-OS/RobotFW-frontend/blob/main/scripts/xsltprocw.sh). This script could check the `includes/` directory and pass the result as a param.

I don't know if this is currently worth the effort, as I currently don't expect the plots to be changing very often. It's more a problem of RobotFW-frontend missing a meaningful README, which is still on my list.

What's your opinion on this?

@MrKevinWeiss I'll fix the `pages.xml` config later today, the plots will appear afterwards

**Comment by ozfox** [comment]
Changed plot names with https://github.com/RIOT-OS/RobotFW-frontend/commit/c98495405e4b9ed6b0ce9f110175996708a6950a

Let me know if you would prefer the `--param` solution and I'll create a Issue for it.

**Comment by MrKevinWeiss** [comment]
We can leave it hard-coded for now

**Comment by MrKevinWeiss** [comment]
https://hil.riot-os.org/results/robotFW_tests/30/overview

Things are looking OK now.  I will verify all the plots.

**Comment by MrKevinWeiss** [comment]
They look good.  Failed tests don't generate the graphs but that is a later problem... Any last words @pokgak or @ozfox ?

**Comment by pokgak** [comment]
Nothing from me.

**Comment by ozfox** [comment]
Looks good to me.
I added [Display error or notification for missing plots on report pages #5](https://github.com/RIOT-OS/RobotFW-frontend/issues/5) to the RobotFW-frontend repo.

**Review by MrKevinWeiss — APPROVED** [review]
ACK!

**Pull request merged**
