### PR TITLE
tests/periph_timer: init debug pins as undef

### PR DESCRIPTION
**Pull request by smlng**
Debugs pins are now initialized at the start with GPIO_UNDEF,
and are then only toggled when properly set to a valid gpio.

This fixes some problems with certain boards, bc default port 0 and pin 0 (PA0) which might have some other function on certain boards and resulted in test failures.

### CODE REVIEW

**Comment by MichelRottleuthner** [comment]
Shouldn't we then do the same for the *set and *clear callbacks?

**Comment by smlng** [comment]
yeah, sure missed them, bc not used right now ... will add

**Comment by smlng** [comment]
amended directly

**Comment by MichelRottleuthner** [comment]
Why is no trace returned properly on so many boards? (e.g. on slstk3401a)

**Comment by smlng** [comment]
debug pins not connected or not correctly connected, @MrKevinWeiss is working on a test to verify DUT pin connections. However, this is unrelated to this PR.

**Pull request merged**
