### PR TITLE
dist/, tests/: rename "skip" tag to "non-critical"

### PR DESCRIPTION
**Pull request by pokgak**
The current "skip" tag are used to mark a failing test that are not fatal to the test suite. However, this can confuse user that the test are skipped/not run at all. This PR renames the "skip" tag to "non-critical" in the RF files and also the `output_to_xunit.py` script.

### Testing Procedure

For `output_to_xunit.py`, there is a test RF suite that can be use. Follow the testing instruction in the README there. The final xunit.xml should have one  test case marked as skipped.

For the changes to RF files, let the HIL CI run through the test. The result should be the same as the nightlies.

### CODE REVIEW

**Comment by ozfox** [comment]
Looks fine, but at the moment the renaming only happens on the input side. The `output_to_xunit.py` still uses the 'skipped' term when generating the output xml. I'd rename the remaining occurrences of 'skipped' to 'failures_non_critical'.

**Comment by MrKevinWeiss** [comment]
So just to be clear, the functionality of the non-critical tests will stay the same it just reads different?

Eventually with robot v4 that support skipped we would rework and be able to get better resolution of what is skipped tests and non-critical?

**Comment by pokgak** [comment]
With this PR currently, it will look for "non-critical" instead of the "skipped" tag from the output.xml. In the final xunit.xml, the non-critical failures count will still be used for the "skipped" property (result.boards.board.testsuite["skipped"]).

Some options that we can choose here:

1. Only change what non-critical failures is called internally ("skipped" -> "non-critical"), the final xunit.xml still uses the "skipped" property to show the count of non-critical failures. This is what is done in this PR.
2. Change the "skipped" property or add new "failures_non_critical" property to the final xunit.xml. This might involve a rework of the parsing logic in `output_to_xunit.py`.

I prefer the first option for now and resolve this difference in "skipped" and "non-critical" later when we really skipped some tests. That said, I don't know how @ozfox uses it in the new output. Thoughts?

**Comment by pokgak** [comment]
Pushed more changes to use "non-critical" when parsing output.xml to avoid confusion. Only when we are building the final xunit.xml we use "skipped" to conform to the current xunit.xml format.

**Comment by MrKevinWeiss** [comment]
How will this affect the current output results in the nightly?

**Comment by pokgak** [comment]
The current nightly output result should not be affected :)

**Comment by MrKevinWeiss** [comment]
Hmmm something doesn't look correct in the robot.xml output...  Could you guys look into it?

**Comment by pokgak** [comment]
I'll look into it

**Comment by pokgak** [comment]
Should be fixed now. Jenkins does not show the xml by default, adding `/*view*` to the end of the URL of the robot.xml shows the xml.

**Comment by MrKevinWeiss** [comment]
please squash

**Comment by pokgak** [comment]
Squashed.

**Review by MrKevinWeiss — APPROVED** [review]
Looks good!

Lets see!

**Comment by pokgak** [comment]
Thanks for the review Kevin :)

**Pull request merged**
