### PR TITLE
tests/periph_uart: full rework

### PR DESCRIPTION
**Pull request by smlng**
This adapts the periph_uart test to use existing keywords and be consistent with other tests.

### CODE REVIEW

**Comment by smlng** [comment]
includes (adapted) proposed changes of #16

**Comment by MrKevinWeiss** [comment]
rebase please

**Comment by smlng** [comment]
done, please wait with merge - I'll run the tests on the HIL and report if good to go

**Comment by smlng** [comment]
okay, this good to go!

**Pull request merged**
