### PR TITLE
common: move test helpers and add args parse helpers

### PR DESCRIPTION
**Pull request by smlng**
this PR move common code from `tests/common` to `util/` and also introduces helper functions for command args parsing.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Seems like some problems, check the CI

**Comment by MrKevinWeiss** [comment]
`sc_arg2int` doesn't have the correct arguments

**Comment by smlng** [comment]
yeah I know, but I now remember that this was going to be ugly/complex to make it type safe, which I first aimed for - let me think about it. I'll fix - you fix the script naming?

**Comment by MrKevinWeiss** [comment]
#45 fix is there, should have checked beforehand...

**Comment by MrKevinWeiss** [comment]
I have a small list of things that I would like (many implemented here but some for later)

- print_cmd
- print_data_dict_str
- print_data_dict_int
- print_data_int
- pint_data_str
- print_result
- print_msg
- print_usage
- print_developer_msg
- parse_gpio_port
- parse_num

**Comment by smlng** [comment]
@MrKevinWeiss have a look again, I guess as a first step this is "good enough". We can improve as we go and update tests

**Comment by MrKevinWeiss** [comment]
The esp32 seems to have some problems with the bool usage.  Should we just fix that later and merge now? Everything else seems good!

**Comment by MrKevinWeiss** [comment]
hmmm seems like some trouble.

**Pull request merged**
