### PR TITLE
chore: bump RIOT version of submodule

### PR DESCRIPTION
**Pull request by smlng**
This is to include latest fixes in periph/i2c for stm32 and kinetis MCUs.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
How much review should we do for this?  Just wait for the CI?

**Comment by smlng** [comment]
yep wait for CI, should be all green now

**Comment by smlng** [comment]
wanna hit merge?

**Comment by smlng** [comment]
or first ACK then merge

**Pull request merged**
